permissions: write-all

name: CI

on:
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v3
   - run: echo "新しい行を追加しました" >> README.txt

   - run: echo add another line
   - run: echo one more 
   - uses: peter-evans/create-pull-request@v5
     with:
      title: update(test)
      branch: main
      commit-message: "this is commit message"
      body: "This pull request updates the README.txt with new lines."
